config/routes.rb
Rails.application.routes.draw do
  # get "about",           to: "pages#about",      as: :about
  # get 'meetings/create'
  # get 'connections/create'
  # get 'startups/index'
  # get 'startups/new'
  # get 'startups/create'
  # get 'investors/new'
  # get 'investors/update'
  # get 'investors/index', to: "investors#index"
  # get 'investors/show'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard", as: :dashboard
  # get 'index', to: "pages#index"

  get "profile", to: "pages#profile", as: :profile
  patch "profile/:id", to:"pages#update_profile", as: :update_profile

  get 'uikit', to: "pages#uikit", as: :uikit

  get 'investors/new', to: "investors#new"
  post 'investors', to: "investors#create"
  # get 'start_up/:id', to: "startups#start_up"
  post 'startups', to: "connections#create"
  get 'startups/form', to: "startups#form", as: :new_startup_registration

  resources :startups do
    resources :connections, only: %i[new create]
  end

  resources :connections, only: %i[update] do
    resources :meetings, only: %i[new create update]
  end


  resources :users do
    resources :investors, only: %i[new create]
  end

  resources :investors, only: %i[edit show update]

  get 'startups/:id/team', to: "startups#team", as: :startup_team
  # resources :startups

  # get '/investors/new', to: "investors#new"
  # post 'investors', to: "investors#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/startup.rb
class Startup < ApplicationRecord
  INDUSTRIES = ["Delivery", "Healthcare Tech", "Artificial Intelligence",
  "Education Technology", "Financial Technology", "Shared Mobility",
  "Supply Chain Management & Logistics", "Real Estate", "Ecommerce",
  "Big Data", "Blockchain Technology", "B2B Software", "Retail"]

  belongs_to :user
  # validates :funding, :funding_round_end, :funding_amount, :industry, :user_id, :headcount, :turnover, presence: true
  has_many :members

  # validates :industry, inclusion: { in: INDUSTRIES }
  after_create :set_type

  # PG Search
  include PgSearch::Model
  pg_search_scope :global_search_startup,
    against: [ :funding, :industry ],
    associated_against: {
      user: [ :company_name, :user_type, :city, :country ]
    },
    using: {
    tsearch: { prefix: true }
    }

  def self.get_distinct(column)
    Startup.select(column.to_sym).distinct.reorder("#{column} ASC")
  end

  def set_type
    self.user.update(user_type: "startup")
  end
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  before_action :set_user, only: %i[new create]
  def show
    @startup = Startup.find(params[:id])
    @connection = Connection.new
  end

  def index
    @startups = @Startup.all
  end

  def team
    @start_up = Startup.find(params[:id])
    @members = @start_up.members
  end

  def form
    @startup = Startup.new
    
  end

  def new
    @user = User.find(params[:user_id])
    @start_ups = Startup.new
  end

  def create
    @start_ups = Start_up.new(startup_params)
    @start_ups.user = @user
    @start_up = Start_up.connection
    if @start_up.save
      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @start_ups = Start_up.find(params[:id])
    @start_ups.destroy
    redirect_to user_path(@start_up.user), status: :see_other
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def starts_up_params
    params.require(:start_up).permit(:content)

  end

end

app/views/startups/_list.html.erb
<div data-controller="animations" data-animations-target="animation"r> <%= render "shared/animation" %>

</div>


<div class="list-startups row" data-controller="cards-show">
  <div class= "list-itself" data-filter-list-target="list">
    <div class="col-8 static">
      <% startups.each do |startup| %>
        <%# add d-none to card-left-details !!!!!  %>
        <div class="card-left-details d-none" style="background-image: linear-gradient(black, black), url(<%= startup.img %>); background-blend-mode: saturation" data-startup="<%= startup.id %>">
          <div class="card-left-info">
            <h2 id="card-left-title"><%= startup.user.company_name %></h2>
            <p id="card-left-desc"><%= startup.bio %></p>
            <ul class="card-left-info-list">
              <li><div id="card-left-industry">
                <p>INDUSTRY</p><p><%= startup.industry %></p>
              </div></li>
              <li><div id="card-left-class">
                <p>CLASS</p><p><%= startup.funding.capitalize %></p>
              </div></li>
              <li><div id="card-left-funding">
                <p>RAISING</p><p><%= startup.funding_amount %></p>
              </div></li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
    <div class= "startups-cards col-4">
      <div class="gallery">
        <% startups.each do |startup| %>
          <div class="card-height" data-startup="<%= startup.id %>">
            <figure class="gallery__item gallery__item--1">
              <%= link_to startup_path(startup.id) do %>
                <img src= "<%= startup.img %>" class="gallery__img" alt="Image 1">
                <div class="card-short-descr">
                  <div class="title-boxed">
                    <h2><%= startup.user.company_name[0..30]%></h2>
                    <h3 class= "startup-industry"><%=startup.industry%></h3>
                  </div>
                </div>
                <div class="class-boxed">
                  <p class= "startup-class"><%=startup.funding %></p>
                </div>
              <% end %>
            </figure>
          </div>

        <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/startups/_show_banner.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon gray-back">
  <div class="container-fluid">

    <div class="d-flex gap-3 align-items-end">
      <div class="startup-font-title"><%= startup.user.company_name.upcase %></div>
      <div class="page-startup-font-title">OVERVIEW</div>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "logo-blue-white.svg", class: "avatar-grey-page dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link"  do %>
              <i class="fa-sharp fa-solid fa-arrow-right-to-bracket"></i>
            <% end %>

          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/startups/create.html.erb
<h1>Startups#create</h1>
<p>Find me in app/views/startups/create.html.erb</p>

app/views/startups/form.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon grey-back">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="/assets/CLOSE-IT WHITE-effe47c314f6869886fb696cdca998e66703898871234bcc6f82d66fb0168762.svg">
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_in">
              <i class="fa-solid fa-arrow-right text-white"></i>
</a>
          </li>
      </ul>
    </div>
  </div>
</div>







<div class= "home-container" >
<div class="start-arrow">

</div>
  <div class="home-description">
    <p>We are a team of motivated professionals working tirelessly to increase startup funding by connecting investors.</p>
  </div>
  <div class="signup-container">
    <div class="joining-as-text">
      <p id="joining-text">JOINING US</p>
      <div class="startup-links">
    

     </div>
    <div class="investor-signup-page ">
     <%= simple_form_for(@startup, method: :post, url: new_startup_registration_path) do |f| %>
        <p class="investor-title">STARTUP</p>

        <div class="form-inputs">
         <%= f.input :industry %>
          <%= f.input :headcount %>
          <%= f.input :turnover %>
          <%= f.input :funding_amount %>
          <%= f.input :funding_round_end_date %>
          <%= f.input :team %>
        </div>

          <div class="form-actions">
            <%= f.button :button, "Next", class: "signup-button" do %>
              <i class="fa-solid fa-arrow-right text-white"></i>
            <% end %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/startups/index.html.erb
<h1>Startups#index</h1>
<p>Find me in app/views/startups/index.html.erb</p>

app/views/startups/new.html.erb
<h1>Startups#new</h1>
<p>Find me in app/views/startups/new.html.erb</p>

app/views/startups/show-backup.html.erb
  <div  class="container home-description">
    <%# 1st row %>
    <div class="d-flex">
      <div class="text-start">
        <p>
          We are a team of motivated professionals working tirelessly to increase startup funding by connecting investors with
          high-potential startups and offering entrepreneurs a platform to showcase their business.
        </p>
      </div>

      <div class="d-flex">
         <img src="https://source.unsplash.com/random/150x200/?portrait" alt="Startup" class="rounded" my-4>
      </div>
      <div>
        <img src="https://source.unsplash.com/random/150x200/?portrait" alt="Startup" class="rounded" my-4>
      </div>
    </div>

    <%# 2nd row %>
     <ul>
      <div class="home-signup">
        <div class="container">

          <div class="d-flex justify-content-between">
          <a href="stylesheets" class="btn btn-primary">5</a>
          <div>

          <h2>PENDING REQUEST</h2>
          </div>
            <a href="stylesheets" class="btn btn-success">3</a>
            <h2> UPCOMIMG MEETINGS</h2>
          </div>

          <div>
            <li><i class="fa-sharp fa-solid fa-arrow-right"></i> <%= link_to "TEAM","#" %>
            <li><i class="fa-sharp fa-solid fa-arrow-right"></i> <%= link_to "ARCHIVE","#"%>
          </div>

        </div>
      </div>
    </ul>
  </div>





  #<ul>
        <div class="graph-container">
         <div class="container justify-space-between">
              <a href="margin-right: 10px" class="btn btn-danger">5</a>
              <li>PENDING REQUEST</li>
            </div>

          <div class="container justify-space-between">
            <a class="btn btn-success">3</a>
              <li>UPCOMIMG MEETINGS</li>
            </div>
            <div class="container justify-space-between">


            <li>Faunding Status</li>
            </div>
            </div>
            <div class="description-text w-25">
              <li><i class="fa-sharp fa-solid fa-arrow-right"></i> <%= link_to "TEAM","#" %>
              <li><i class="fa-sharp fa-solid fa-arrow-right"></i> <%= link_to "ARCHIVE","#"%>
            </div>

app/views/startups/show.html.erb
<div class="container">

  <div class="header-container">
    <%= render "show_banner", startup: @startup%>
  </div>

  <% if current_user.user_type == "investor" %>
      <div class= "links-plus-description">
        <div class= "description-startup-boxes">
          <div class="row">
              <div class="industry-boxed">
                <p><%= @startup.industry %></p>
              </div>
          </div>
            <div class="funding-boxed">
              <div class="column">
                  <p><%= @startup.funding %></p>
              </div>
            </div>
        </div>
        <div class="all-startup-link">
            <h2 class="home-line-link">
            <i class="fa-sharp fa-solid fa-arrow-left"></i>
            <%= link_to "ALL STARTUPS", root_path, class: "white-link"%>
        </div>
      </div>
      <div class="startup-info-container">
            <div class="row">
              <div class= "card-startup-descripion" >
                  <h2><%= @startup.user.company_name[0..30]%></h2>
                  <p> <%= @startup.bio %></p>
                  <%# <h3>About <%= @startup.user.company_name[0..30]%> </h3>
              </div>


             <div class= "countdown-border" >
                  Headcount
                  <div class="countdown-box">
                    <table id= "countdown" >
                      <tr id="countdown-timer">
                        <td><span id= "days">x</span></td>
                        <td><span id= "hours">x</span></td>
                        <td><span id= "minutes">x</span></td>
                        <td><span id= "seconds">x</span></td>
                      </tr>
                      <tr id="countdown-labels">
                        <td><span>Days</span></td>
                        <td><span>Hours</span></td>
                        <td><span>Minutes</span></td>
                        <td><span>Seconds</span></td>
                      </tr>
                    </table>
                  </div>

               <script>
                  const raisingDeadline = new Date('jan 01, 2024 00:00:00');

                  setInterval(function() {
                    setCountdown(raisingDeadline);
                  },1000)

                  function setCountdown(countingDownTime) {

                    let now = new Date();
                    let timeRemaining = countingDownTime - now

                    let seconds = Math.floor(timeRemaining / 1000);
                    let minutes = Math.floor(timeRemaining / (1000*60));
                    let hours = Math.floor(timeRemaining / (1000*60*60));
                    let days = Math.floor(timeRemaining / (1000*60*60*24));

                    // console.log(days, hours, minutes, seconds);

                    let daysToDisplay = days;
                    let hoursToDisplay = hours - (days * 24);
                    let minutesToDisplay = minutes - (hours * 60);
                    let secondsToDisplay = seconds - (minutes * 60);

                   // console.log(daysToDisplay, hoursToDisplay, minutesToDisplay, secondsToDisplay);

                    const daysEl = document.getElementById('days');
                    const hoursEl = document.getElementById('hours');
                    const minutesEl = document.getElementById('minutes');
                    const secondsEl = document.getElementById('seconds');

                    daysEl.textContent = daysToDisplay;
                    hoursEl.textContent = hoursToDisplay;
                    minutesEl.textContent = minutesToDisplay;
                    secondsEl.textContent = secondsToDisplay;
                  }
                </script>

              </div>

              <% percent = (@startup.raised_amount/@startup.funding_amount)*100 %>

              <div class= "raising-funding-box" >
                  Raising status

                <div class="col-12 progress-bar" id="myProgress">
                  <div id="myBar" style="width: <%= percent %>%;"></div>
                </div>

                <span id=raising_per><%= percent.floor %> %</span>

              </div>
            </div>

          <div class="container-dx">

            <div class="description-image">
              <div class="img-dx">
                  <div class="column">
                    <img src="https://source.unsplash.com/random/150x200/?portrait" alt="Startup">

                    <div class="img-sx">
                      <img src="https://source.unsplash.com/random/150x200/?portrait" alt="Startup">
                    </div>
                  </div>
                </div>
            </div>

             <%= render "connections/new", startup: @startup, connection:@connection%>

            <div class="team-link">
             <h2 class="team-line-link">
             <i class="fa-sharp fa-solid fa-arrow-right"></i>
             <%= link_to "TEAM", startup_team_path(@startup), class: "white-link"%>
            </div>
          </div>
      </div>

  <% else %>
    <div class="description-container d-flex mt-5">
      <div class="description-text w-75">

        We are a team of motivated professionals working tirelessly to increase startup funding by connecting investors with
        high-potential startups and offering entrepreneurs a platform to showcase their business.

        <div class="graph-two" style="padding-left: 20px;">
          <div class="border pt-4 px-3 graph-box">
            <div class="d-flex justify-content-end h-100 align-items-end">
              <div class="chart">
                <div class="chart-inside"></div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-items-between">
            <p>Founding status</p>
            <p>43%</p>
          </div>

        </div>

        <div class="pl-4 pt-5 graph-three" style="padding-left: 20px;">
          <h2 class="d-flex border-top p-3 align-items-center mb-0"><i class="fa-sharp fa-solid fa-arrow-right"></i><a href="#" class="white-link">TEAM</a></h2>
          <h2 class="d-flex border-top border-bottom p-3 align-items-center"><i class="fa-sharp fa-solid fa-arrow-right"></i><a href="#" class="white-link">ARCHIVE</a></h2>
        </div>
      </div>

      <div class="description-image">
          <img src="https://source.unsplash.com/random/150x200/?portrait" alt="Startup" class="rounded mr-4">
      </div>

      <div class="description-image">
        <img src="https://source.unsplash.com/random/150x200/?portrait" alt="Startup" class="rounded"style="margin-left:10px;" >
      </div>


    <div class="d-flex justify-content-between pt-4">
        <div class="graph-one">
          <div class="border p-4 d-flex graph-box justify-content-evenly align-items-center">
            <div class="w-50 border-end px-5">
              <p class="fs-1 fw-bold bg-white text-center p-1" style="color: red;">5</p>
              <p>PENDING <br>REQUEST</p>
            </div>

            <div class="w-50 px-5">
              <p class="bg-white fw-bold text-center p-1 fs-1" style="color:green;">3</p>
              <p>UPCOMIMG <br>MEETINGS</p>
            </div>
          </div>
          <p> Requests Status</p>
        </div>

        <div class="graph-two" style="padding-left: 20px;">
          <div class="border pt-4 px-3 graph-box">
            <div class="d-flex justify-content-end h-100 align-items-end">
              <div class="chart">
                <div class="chart-inside"></div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-items-between">
            <p>Founding status</p>
            <p>43%</p>
          </div>

        </div>

        <div class="pl-4 pt-5 graph-three" style="padding-left: 20px;">
          <h2 class="d-flex border-top p-3 align-items-center mb-0"><i class="fa-sharp fa-solid fa-arrow-right"></i><a href="#" class="white-link">TEAM</a></h2>
          <h2 class="d-flex border-top border-bottom p-3 align-items-center"><i class="fa-sharp fa-solid fa-arrow-right"></i><a href="#" class="white-link">ARCHIVE</a></h2>
        </div>
      </div>
   </div>
<% end %>
</div>

<% blue_pages = current_page?(root_path) || current_page?(new_user_session_path)|| current_page?(user_session_path) %>
<div class="footer grey-back d-none <%= 'blue-back' if blue_pages %>">
<div class="footer-links">
  <a href="#"><i class="fab fa-github"></i></a>
  <a href="#"><i class="fab fa-instagram"></i></a>
  <a href="#"><i class="fab fa-facebook"></i></a>
  <a href="#"><i class="fab fa-twitter"></i></a>
  <a href="#"><i class="fab fa-linkedin"></i></a>
</div>
<div class="footer-copyright">
</div>

app/views/startups/start_up.html.erb
<div class= "home-container">

  <% if user_signed_in? %>
    <% #if current_user.user_type == "start-up" %>
      <div class="search-list-user" data-controller="filter-list">
        <%= render 'search/startup_search' %>
        <%= render "user/list", user: @users %>
      </div>
    <% #else %>

    <% #end %>


  <% else %>
    <div class="home-description">
      <p id="white-text">We stand alongside all organizations that’ve achieved so much for the community, and we continue to learn from them. It'll take a lot more listening and a load more action but, together with them, we're taking a small step that we hope to make a big difference in our everyday lives.</p>
    </div>
    <div class="home-signup">
      <ul>
      <li>SIGN UP AS</li>
      <li><i class="fa-sharp fa-solid fa-arrow-right"></i> <%= link_to "START UP",  new_user_registration_path  %></li>
      <li><i class="fa-sharp fa-solid fa-arrow-right"></i> <%= link_to "INVESTOR",  new_user_registration_path %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/startups/team.html.erb
<%= render "shared/navbar" %>
<%# <div></div>
 <%= link_to root_path, class: "navbar-brand" do %>

 <div class="startup-link">
      <h2 class="startup-line-link">
      <i class="fa-sharp fa-solid fa-arrow-left"></i>
      <%= link_to "STARTUP", :back, class: "white-link"%>
  </div>

<div class="members-cointainer row members-gap">

  <div class="col-6" data-controller="team-show">
    <% @members.each do |member| %>
      <div class= "description-team-members d-none info-card-<%= member.id %>"%>
        <div class= "card-member-descripion" >
          <h1> <%= member.first_name %> <%= member.last_name %></h1>
          <p> <%= member.bio %></p>
          <h2>Role</h2>
          <p><%= member.position %></p>
        </div>
      </div>
    <% end %>
  </div>

  <div class= "col-4" data-filter-list-target="list">
    <div class= "members-cards">
      <div class="gallery ">
        <% @members.each do |member| %>
          <div class="card-height profile-card" data-id=<%= member.id %>>
            <figure class="gallery__item gallery__item--1">
              <img src="https://source.unsplash.com/random/300x300/?portrait&<%= rand(1...100) %>" class="gallery__img" alt="Image 1">
              <div class="card-member-name">
                <div class="name-boxed">
                  <h3 class= "member-name"><%=member.first_name%> <%=member.last_name%></h3>
              </div>
            </figure>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>