config/routes.rb
Rails.application.routes.draw do
  # get "about",           to: "pages#about",      as: :about
  # get 'meetings/create'
  # get 'connections/create'
  # get 'startups/index'
  # get 'startups/new'
  # get 'startups/create'
  # get 'investors/new'
  # get 'investors/update'
  # get 'investors/index', to: "investors#index"
  # get 'investors/show'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard", as: :dashboard
  # get 'index', to: "pages#index"

  get "profile", to: "pages#profile", as: :profile
  patch "profile/:id", to:"pages#update_profile", as: :update_profile

  get 'uikit', to: "pages#uikit", as: :uikit

  get 'investors/new', to: "investors#new"
  post 'investors', to: "investors#create"
  # get 'start_up/:id', to: "startups#start_up"
  post 'startups', to: "connections#create"
  get 'startups/form', to: "startups#form", as: :new_startup_registration

  resources :startups do
    resources :connections, only: %i[new create]
  end

  resources :connections, only: %i[update] do
    resources :meetings, only: %i[new create update]
  end


  resources :users do
    resources :investors, only: %i[new create]
  end

  resources :investors, only: %i[edit show update]

  get 'startups/:id/team', to: "startups#team", as: :startup_team
  # resources :startups

  # get '/investors/new', to: "investors#new"
  # post 'investors', to: "investors#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/_button.html.erb
<div class="btn btn-primary">hello</div>

app/views/pages/_calendar.html.erb
<div class="simple-calendar">
  <%= month_calendar(events: @meetings) do |date, meetings| %>
    <% if date.today? %>
      <div id="today"><%= date.strftime("%d").to_i %></div>
    <% else %>
      <div class="other-days"><%= date.strftime("%d").to_i %></div>
    <% end %>
    <div class="date-info">
      <% meetings.each do |meeting| %>
        <% if meeting.title.length > 25 %>
          <p><%= meeting.start_time.strftime("%H:%M%p").downcase %> <%= meeting.title.first(30) %>...</p>
        <% else %>
          <p><%= meeting.start_time.strftime("%H:%M%p").downcase %> <%= meeting.title %></p>
        <% end %>
      <% end %>
    </div>

  <% end %>
</div>

app/views/pages/_show_meetings.html.erb
<% if connection_meetings != nil %>
    <% accepted_meetings = connection_meetings.where(meeting_accepted: true) %>
    <% declined_meetings = connection_meetings.where(meeting_accepted: false) %>
    <% accepted_meetings.each do |accepted| %>

    <% end %>
    <% declined_meetings.each do |declined| %>

    <% end %>
  <% else %>

<% end %>

app/views/pages/dashboard.html.erb
<div>
   <%= render 'calendar' %>
</div>
<div class="container-dashboard">
  <div class="requests-left">
    <div id="requests-left-title">
      <h1>RECEIVED CONNECTIONS</h1>
    </div>
    <div class="requests-content-container">
      <% counter = 0 %>
      <% @my_connection_requests_received.each do |request| %>
        <% counter += 1 %>
        <%# <% raise %>
        <% if request.pending == true %>
        <div class="forms-container">
          <img class="requester-img" src="https://source.unsplash.com/random/400x400/?industrye&<%= rand(1...100) %>">
          <div class="requester-info">
            <p>Company name: <%= User.where(id:request.sender_id).select(:company_name).first.company_name %></p>
            <div class="requester-status">
              <%= render 'connections/accept', request: request, counter: counter %>
              <%= render 'connections/decline', request: request, counter: counter %>
            </div>
          </div>
        </div>
        <% else %>
          <% if request.pending == false && request.accepted == true %>
            <div class="forms-container">
              <img class="requester-img" src="https://source.unsplash.com/random/400x400/?industrye&<%= rand(1...100) %>">
              <div class="requester-info">
                <p>Company name: <%= User.where(id:request.sender_id).select(:company_name).first.company_name %></p>
                 <div class="requester-status">
                  <div class="btn btn-outline-success accepted">Accepted!</div>
                  <%# Bootstrap %>
                  <button type="button" class="btn btn-primary meeting-set" data-toggle="modal" data-target="#exampleModal<%=counter%>">
                    Set up a meeting!
                  </button>
                </div>
              </div>
            </div>
            <%= render 'meetings/popup', counter: counter, request: request %>
            <%# Bootstrap %>
            <%# Check if there is a meeting already set%>
            <% meetings = @meetings.where(connection_id: request) %>
            <% connection_meetings = meetings.where(meeting_pending: false) %>
            <%= render 'show_meetings', connection_meetings: connection_meetings, request: request, counter: counter %>
          <%# elsif request.pending == false && request.accepted == false %>
            <%# <div class="btn btn-outline-danger">Declined!</div> %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="requests-right">
    <div id="requests-right-title">
      <h1>SENT CONNECTIONS</h1>
    </div>
    <div class="requests-content-container">
      <% counter = 0 %>
      <% @my_connection_requests_sent.each do |request| %>
        <% counter += 1 %>
          <% if request.pending == true %>
            <div class="forms-container2">
              <img class="requester-img" src="https://source.unsplash.com/random/400x400/?industrye&<%= rand(1...100) %>">
              <div class="requester-info">
                <p>Company name: <%= User.where(id:request.receiver_id).select(:company_name).first.company_name %></p>
                <div class="btn btn-outline-warning pending">Pending</div>
              </div>
            </div>
          <% else %>
            <% if request.pending == false && request.accepted == true %>
              <div class="forms-container2">
                <img class="requester-img" src="https://source.unsplash.com/random/400x400/?industrye&<%= rand(1...100) %>">
                <div class="requester-info">
                  <p>Company name: <%= User.where(id:request.sender_id).select(:company_name).first.company_name %></p>
                  <div class="requester-status">
                    <div class="btn btn-outline-success accepted-right">Accepted!</div>
                    <button type="button" class="btn btn-primary metting-right" data-toggle="modal" data-target="#exampleModal<%=counter%>">
                      Set up a meeting!
                    </button>
                  </div>
                </div>
              </div>
              <%= render 'meetings/popup', counter: counter, request: request %>
              <% meetings = @meetings.where(connection_id: request) %>
              <% connection_meetings = meetings.where(meeting_pending: false) %>
              <%= render 'show_meetings', connection_meetings: connection_meetings, request: request, counter:counter %>
            <% elsif request.pending == false && request.accepted == false %>
              <div class="forms-container2">
                <img class="requester-img" src="https://source.unsplash.com/random/400x400/?industrye&<%= rand(1...100) %>">
                <div class="requester-info">
                  <div class="btn btn-outline-danger">Declined!</div>
                </div>
              </div>
            <% end %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

<% blue_pages = current_page?(root_path) || current_page?(new_user_session_path)|| current_page?(user_session_path) %>
<div class="footer grey-back d-none <%= 'blue-back' if blue_pages %>">
<div class="footer-links">
  <a href="#"><i class="fab fa-github"></i></a>
  <a href="#"><i class="fab fa-instagram"></i></a>
  <a href="#"><i class="fab fa-facebook"></i></a>
  <a href="#"><i class="fab fa-twitter"></i></a>
  <a href="#"><i class="fab fa-linkedin"></i></a>
</div>
<div class="footer-copyright">
</div>

app/views/pages/home.html.erb
<div data-controller="animation-logout" data-animation-logout-target="animation" > <%= render "shared/animationlogout" %>

</div>
<div class= "home-container">

  <% if user_signed_in? %>
    <% if current_user.user_type == "investor" %>
      <div class="search-list-startup" data-controller="filter-list">
        <%= render 'search/startup_search' %>
        <%= render "startups/list", startups: @startups %>
      </div>
    <% else %>

    <% end %>


  <% else %>
    <div class="home-description">
      <p id="white-text">We are a team of motivated professionals working tirelessly to increase startup funding by connecting investors.</p>
    </div>
    <div class="home-signup">
      <ul>
      <li>SIGN UP AS</li>
      <li><i class="fa-sharp fa-solid fa-arrow-right"></i> <%= link_to "START UP",  new_startup_registration_path  %></li>
      <li><i class="fa-sharp fa-solid fa-arrow-right"></i> <%= link_to "INVESTOR",  new_user_registration_path %></li>
      </ul>
    </div>
  <% end %>

</div>

app/views/pages/index.html.erb
<h1>Here we are</h1>

app/views/pages/profile.html.erb
<div class= "home-container">
  <div class="signup-container">
    <div class="investor-edit-page">
      <div class="investor-as-text">
        <p id="investor-text">EDIT YOUR INFO AS A</p>
      </div>
      <%= simple_form_for @investor do |f| %>
        <p class="investor-title">INVESTOR</p>
        <%= f.collection_select :investor_type, Investor::INVESTORS, :to_s, :titleize, { include_blank: 'Select investor type' } %>
        <%= f.collection_select :funding_type, Investor::FUNDINGS, :to_s, :titleize, { include_blank: 'Select funding type' } %>
        <%= f.input :private, disabled: false %>
        <div class="form-actions">
          <%= f.button :button, class: "create-button" do %>
            <i class="fa-solid fa-check"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    </div>
  </div>
  <div class="signup-container">
    <div class="home-signup-page">
      <div class="user-as-text">
        <p id="user-text">EDIT YOUR INFO AS A</p>
      </div>
      <%= simple_form_for @user, method: :patch, url: update_profile_path(@user) do |f| %>
        <%= f.error_notification %>
        <p class="user-edit-title">USER</p>
        <div class="form-inputs">
          <%= f.input :email, required: true, autofocus: true %>

          <%= f.input :first_name,
                      hint: "",
                      required: false,
                      input_html: { autocomplete: "first name" } %>

          <%= f.input :last_name,
                      hint: "",
                      required: false,
                      input_html: { autocomplete: "last name" } %>

          <%= f.input :address,
                      hint: "",
                      required: false,
                      input_html: { autocomplete: "address" } %>

          <%= f.input :city,
                      hint: "",
                      required: false,
                      input_html: { autocomplete: "city" } %>

            <label class="country-label" for="">Country</label>
           <%= f.text_field :country,
                      hint: "",
                      required: false,
                      class: "form-control string optional",
                      input_html: { autocomplete: "country" } %>

          <%= f.input :company_name,
                      hint: "",
                      required: false,
                      input_html: { autocomplete: "company-name" } %>

          <%#= f.input :password,
                      hint: "leave it blank if you don't want to change it",
                      required: false,
                      input_html: { autocomplete: "new-password" } %>
          <%#= f.input :password_confirmation,
                      required: false,
                      input_html: { autocomplete: "new-password" } %>
          <%= f.input :current_password,
                      hint: "we need your current password to confirm your changes",
                      required: true,
                      input_html: { autocomplete: "current-password" } %>
        </div>

        <div class="form-actions">
          <%= f.button :button, "Next", class: "signup-button" do %>
            <i class="fa-solid fa-check"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <%# <h3>Cancel my account</h3> %>

    <%# <div>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete %></div>

      <%# <%=link_to "Back", :back %>

    <%# </div>  %>
  </div>
</div>
<% blue_pages = current_page?(root_path) || current_page?(new_user_session_path)|| current_page?(user_session_path) %>
<div class="footer grey-back d-none <%= 'blue-back' if blue_pages %>">
<div class="footer-links">
  <a href="#"><i class="fab fa-github"></i></a>
  <a href="#"><i class="fab fa-instagram"></i></a>
  <a href="#"><i class="fab fa-facebook"></i></a>
  <a href="#"><i class="fab fa-twitter"></i></a>
  <a href="#"><i class="fab fa-linkedin"></i></a>
</div>
<div class="footer-copyright">
</div>

app/views/pages/test.html.erb
<%= simple_form_for(request) , data: { update_pending_requests_target: "form"}do |f| %>
  <%= f.input :pending, :as => :hidden, :input_html => { :value => false , data: {update_pending_requests_target: "pending"}} %>
  <%= f.input :accepted, :as => :hidden, :input_html => { :value => true , data: {update_pending_requests_target: "accepted"}} %>
  <%= f.button :submit, "Accept", class: "btn btn-success"%>
<% end %>
<%= simple_form_for(request), data: { update_pending_requests_target: "form"} do |f|  %>
  <%= f.input :pending, :as => :hidden, :input_html => { :value => false , data: {update_pending_requests_target: "pending"}} %>
  <%= f.input :accepted, :as => :hidden, :input_html => { :value => false , data: {update_pending_requests_target: "accepted"}} %>
  <%= f.button :submit, "Decline", class: "btn btn-danger"%>
<% end %>

app/views/pages/uikit.html.erb
<%= render "shared/navbar" %>
<%= render "shared/footer" %>
<%= render "pages/card" %>